import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BottomNav from '@/components/BottomNav'


  
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body className="bg-black pb-24"> {/* أضفنا padding bottom لكي لا يغطي الشريط المحتوى */}
        {children}
        <BottomNav />
     </body>
    </html>
  )
}

 
